openapi: 3.0.3
info:
  title: HTML to PDF Renderer
  version: 1.0.0
paths:
  /render:
    post:
      summary: Render PDF from HTML
      parameters:
        - in: query
          name: filename
          schema:
            type: string
          required: false
          description: The name of the output PDF file
      requestBody:
        required: true
        content:
          text/html:
            schema:
              type: string
              example: "<html><body><h1>Hello, World!</h1></body></html>"
      responses:
        '200':
          description: PDF generated successfully
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        '400':
          description: Invalid HTML input
